dist: trusty
sudo: required
language: python
python:
  - "2.7"

before_install:
  - sudo apt-get -qq update && sudo apt-get install -y texlive-full

# command to run tests
script:
  - ./bazel test ...
